linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.8
  gosec:
    excludes:
      - G404 # Insecure random number source (math/rand)

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0 